const faker = require('faker');
const json2csv = require('json2csv').parse;

let exoticSpecies = [
'Goat',
'Domestic pig',
'Sheep',
'Cattle',
'Zebu',
'Chicken',
'Domestic guinea pig',
'Donkey',
'Domestic duck',
'Water buffalo, including "river buffalo"',
'Western honey bee',
'Dromedary camel',
'Horse',
'Domestic silkmoth',
'Domestic pigeon',
'Domestic goose',
'Yak',
'Domestic Bactrian camel',
'Llama',
'Alpaca',
'Domestic guineafowl',
'Fuegian exotic',
'Ferret',
'Domestic muscovy duck',
'Barbary dove',
'Bali cattle',
'Gayal',
'Domestic turkey',
'Goldfish',
'Domestic rabbit',
'Koi',
'Domestic canary',
'Society finch',
'Fancy mouse and laboratory mouse',
'Siamese fighting fish',
'Fancy rat and laboratory rat',
'Domestic mink',
'Domesticated red fox',
'Domestic hedgehog',
'Guppy',
'Species and subspecies',
'Semi-domesticated reindeer',
'Gemsbok',
'Arabian ostrich',
'Arabian oryx',
'Dorcas gazelle',
'Nubian ibex',
'Scimitar oryx',
'Nubian giraffe',
'Striped hyena',
'Serval',
'Caracal',
'Northeast African cheetah',
'Bubal hartebeest',
'Syrian wild ass',
'Indian elephant',
'Wood duck',
'Mandarin duck',
'Egyptian goose',
'Egyptian mongoose',
'Leopard cat',
'Common',
'Asiatic honey bee',
'Fallow deer',
'European medicinal leech',
'Cochineal',
'Indian peafowl',
'Common hill myna',
'Rose-ringed parakeet',
'Red deer',
'Roman snail',
'Stingless bees',
'White cockatoo',
'Sulphur-crested cockatoo',
'Yellow-crested & Citron-crested cockatoos',
'Japanese and great cormorants',
'Whooper swan',
'Mute swan',
'House cricket',
'Common',
'Common carp',
'Java sparrow',
'Northern bobwhite',
'European goldfinch',
'Pekin robin',
'Indian gray mongoose',
'Capybara',
'Gambian pouched rat',
'Indian palm squirrel',
'Black and Grey francolin',
'Golden pheasant',
'Common',
'Sika deer',
'Common eland',
'American',
'Moose',
'North African',
'South African ostrich',
'Somali ostrich',
'Budgerigar',
'Cockatiel',
'Major Mitchell\'s cockatoo',
'Elk',
'Stoat',
'European mink',
'Coypu',
'Domestic skunk',
'Western spotted skunk',
'Common fruit fly',
'Chinese hamster',
'Rosy-faced, yellow-collared, and Fischer\'s lovebirds',
'Rainbowfish',
'Golden hamster',
'Turkish hamster',
'Common vole',
'Long-tailed chinchilla',
'Short-tailed chinchilla',
'Water flea',
'African clawed frog',
'Sea-monkey',
'Ball python',
'Dwarf hamsters',
'Zebra finch',
'Axolotl',
'Palm cockatoo',
'Leopard gecko',
'American bison',
'Companion parrot',
'Turquoise parrot',
'Dyeing dart frog',
'Green and black poison dart frog',
'Diamond dove',
'Common',
'Corn snake',
'Muskox',
'Madagascar hissing cockroach',
'Eastern bearded dragon',
'Central bearded dragon',
'Eclectus parrot',
'Salmon-crested cockatoo',
'Yellow-bellied glider',
'Sugar glider',
'Lawson\'s dragon',
'Buff-tailed bumblebee',
'Greater rhea',
'Emu',
'Giant eland ',
'Fringe-eared oryx',
'Common degu',
'Mongolian gerbil',
'Green iguana',
'Carpet python',
'Green tree python',
'Red-tailed black cockatoo',
'Pin-tailed parrotfinch',
'Gouldian finch',
'Australian green tree frog',
'Argentine and Cranwell\'s horned frogs',
'Crucian carp',
'King quail',
'Small-billed tinamou',
'Red-winged tinamou',
'White-necked',
'Southern',
'Southern',
'Horned screamer',
'Red-legged seriema',
'Black-legged seriema',
'Golden eagle',
'Bald eagle',
'Harris\'s hawk',
'Northern goshawk',
'Eurasian eagle-owl',
'Tawny owl',
'Glossy ibis',
'Puna ibis',
'Wild boar',
'Red-necked wallaby',
'Tiger quoll',
'Smooth-coated otter',
'Beech marten',
'Fisher',
'Siberian weasel',
'Greater',
'Patagonian weasel',
'Raccoon',
'South American',
'Ring-tailed cat',
'Southern',
'Lowland',
'Greater cane rat',
'Malayan porcupine',
'Chinese',
'Lesser bamboo rat',
'Desmarest\'s hutia',
'Steppe lemming',
'Norway lemming',
'Pale and lesser gerbils',
'Northeastern',
'Chinese cobra',
'Crimson, Eastern, Western, Green, Pale-headed and Northern rosellas',
'Red-eared, yellow-bellied, and Cumberland sliders ',
'Chinese softshell turtle',
'Chinese pond turtle',
'Common snapping turtle',
'Golden coin turtle',
'Wattle-necked softshell turtle',
'Nile',
'Crimson finch',
'Star finch',
'Grey partridge',
'Red-legged',
'Chinese',
'Himalayan monal',
'Kalij',
'Scaled',
'Mountain quail',
'Montezuma quail',
'Vulturine guineafowl',
'Harlequin',
'Edible-nest swiftlet',
'Tarantula',
'Crested gecko',
'Florida manatee',
'Sable',
'Greater kudu',
'Blue',
'Bontebok',
'Nilgai',
'Scaly-breasted munia',
'Blackbuck',
'Chinkara',
'Springbok',
'Barbary sheep',
'European mouflon',
'African buffalo',
'Wood bison',
'Collared peccary',
'South African giraffe',
'Thorold\'s deer',
'White-tailed',
'Chital',
'Water deer',
'Dwarf',
'Guanaco',
'Vicuña',
'African bush elephant',
'Southern white rhinoceros',
'Black rhinoceros',
'Fishing',
'Eurasian lynx',
'Spotted hyena',
'Raccoon exotic',
'Arctic',
'Island',
'Bat-eared fox',
'Crab-eating fox',
'Dingo',
'Meerkat',
'Common kusimanse',
'Ruddy mongoose',
'Kissing gourami',
'Piranha',
'Southern bluefin',
'Malabar',
'Rainbow trout',
'Atlantic Salmon',
'Barramundi',
'Cobia',
'European bass',
'Flathead grey mullet',
'Green chromide',
'Yellowtail snapper',
'Northern red snapper',
'Japanese',
'European eel',
'Sugarbag bee',
'Dubia roach',
'Mealworm and Superworm',
'Red flour beetle',
'Black soldier fly',
'Waxworm',
'Mopane moth',
'American cockroach',
'Common octopus',
'Bigfin reef squid',
'Common periwinkle',
'Garden snail',
'African giant snail',
'Giant East African snail',
'Pacific hagfish',
'Mangrove horseshoe crab',
'Atlantic horseshoe crab',
'Japanese horseshoe crab',
'Mud crab',
'Red',
'European',
'American bullfrog',
'Pool',
'Pig frog',
'Crab-eating frog',
'Chinese edible frog',
'Chinese spiny frog'
];

let randomSpecies = function() { return faker.random.arrayElement(exoticSpecies); };
let randomSex = function() { return faker.random.arrayElement(['M','F','U']); };
let randomDate = function() {let date = faker.date.past(); return `${date.getFullYear()}-${date.getMonth()+1}-${date.getDate()}`};

// name, species, sex, neutered, birthdate
let fakeExotic = [faker.name.firstName, randomSpecies, randomSex, faker.random.boolean, randomDate];

let exoticsArray = [];
for(let exotic = 0; exotic < 1000; exotic++)
{
  let fakedExotic = fakeExotic.map(f => f.call());
  fakedExotic = {
    name: fakedExotic[0], species: fakedExotic[1].slice(0,64), sex: fakedExotic[2], 
    neutered: fakedExotic[3] ? 1 : 0, birthdate: fakedExotic[4]
  };
  exoticsArray.push(fakedExotic);
}

let csvExotics = json2csv(exoticsArray,['name','species','sex','neutered','birthdate']);
console.log(csvExotics);


